version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment: 
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
    ports: 
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s -u http://localhost:9200/_cat/health | grep -q 'green'
      interval: 10s
      retries: 18
    volumes:
      - es-data:/usr/share/elasticsearch/data
volumes:
  es-data: 
    driver: local
